// @ts-check
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import eslintPluginAstro from "eslint-plugin-astro";

export default tseslint.config(
  // Don't lint build output, generated types, or the Playwright artifacts.
  {
    ignores: [
      "dist/",
      ".astro/",
      "node_modules/",
      "coverage/",
      "playwright-report/",
      "test-results/",
    ],
  },

  // Base JS + type-aware TypeScript rules.
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  // Astro components. Wires up astro-eslint-parser, the recommended Astro
  // rules, and (via parserOptions below) the TS frontmatter type information.
  ...eslintPluginAstro.configs.recommended,

  // Enable type-aware linting. `projectService` resolves each file against the
  // nearest tsconfig automatically; `.astro` files need to be declared as an
  // extra extension so the TS program will include their frontmatter.
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
        extraFileExtensions: [".astro"],
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  // The TS compiler already resolves ambient types (e.g. `ImageMetadata`), so
  // core `no-undef` only produces false positives on typed Astro frontmatter.
  {
    files: ["**/*.astro"],
    rules: {
      "no-undef": "off",
    },
  },

  // env.d.ts is generated by Astro and uses triple-slash references by design.
  {
    files: ["**/*.d.ts"],
    rules: {
      "@typescript-eslint/triple-slash-reference": "off",
    },
  },

  // Turn off the type-aware rules where full type information isn't reliably
  // available: .astro frontmatter (astro-eslint-parser can't reconstruct
  // Astro's generated types), and the JS config files and Playwright specs
  // (e2e is excluded from tsconfig.json) which live outside the typed project.
  {
    files: ["**/*.astro", "**/*.{js,mjs,cjs}", "e2e/**/*.ts"],
    extends: [tseslint.configs.disableTypeChecked],
  },
);
